version: '3'

services:
  # Database container
  wildbreeze-mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'

  # RabbitMQ container
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
