openapi: 3.0.1
info:
  title: safety-intelligence-service
  description: Service contract for safety-intelligence-service with OpenAPI 3.0 specifications
  version: 1.0.0
servers:
  - url: 'http://localhost:8000/safety-intelligence/api'
  - url: 'http://localhost:8014/api'
  - url: 'http://18.217.249.183/safety-intelligence/api'
tags:
  - name: Safety Intelligence
security:
  - bearerAuth: []
paths:
  /health:
    get:
      security: []
      tags:
        - Health
      description: Gets health of the service
      responses:
        200:
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
        default:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: All requests against Kong Gateway must include the `Authorization` header containing your JWT Token.
  schemas:
    ExtendedErrorInfo:
      required:
        - message
      properties:
        message:
          type: string
        type:
          type: string
        key:
          type: string
        property:
          type: string
    Error:
      required:
        - message
      type: object
      properties:
        extraInfo:
          type: array
          items:
            $ref: '#/components/schemas/ExtendedErrorInfo'
        message:
          type: string
    HealthCheckResponse:
      required:
        - serviceName
        - status
      type: object
      properties:
        serviceName:
          type: string
        status:
          type: string
        uptime:
          type: number
        timestamp:
          type: string
        pid:
          type: integer
          format: int32
